package com.hammam.attendai.security

object PermissionCatalog {
    val all = setOf(
        "VIEW_STUDENTS","EDIT_STUDENTS","START_LECTURE","END_LECTURE","EDIT_ATTENDANCE","APPROVE_ATTENDANCE",
        "VIEW_REPORTS","SEND_REPORTS","APPROVE_REPORT","MANAGE_REPORT_SETTINGS","MANAGE_TEACHERS","MANAGE_SUBJECTS",
        "MANAGE_SETTINGS","VIEW_AUDIT_LOG","EXPORT_AUDIT_LOG","MANAGE_USERS","MANAGE_ROLES","MANAGE_PERMISSIONS",
        "MANAGE_ACADEMIC_STRUCTURE","MANAGE_TIMETABLE","TAKE_OVER_ATTENDANCE","MANAGE_AI_PROVIDER","MANAGE_BACKUP",
        "MANAGE_CONFIGURATION","RUN_DATA_INTEGRITY","RESTORE_BACKUP","SUBMIT_APPEAL","REVIEW_APPEALS",
        "EDIT_FROZEN_ATTENDANCE","MANAGE_DEVICE_ENROLLMENT","VIEW_SYSTEM_HEALTH"
    )
}
